AdventureWorks/Models/EmployeeDepartmentHistorys.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AdventureWorks.Models
{
    public class EmployeeDepartmentHistorys
    {
        [Key]
        public int BusinessEntityID { get; set; }
        public int DepartmentID { get; set; }
        public string Name { get; set; }
        public int ShiftId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime ModificationDate { get; set; }
}
}

AdventureWorks/Models/Employees.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AdventureWorks.Models
{
    public class Employees
    {
        [Key]
        public int BusinessEntityID { get; set;}
        public string EmployeeID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LoginID { get; set; }
        public short? OrganizationLevel { get; set; }
        public string JobTitle { get; set; }
        public DateTime? BirthDate { get; set; }
        public string Gender { get; set; }
        public DateTime? HireDate { get; set; }
        public DateTime? ModificationDate {  get; set; }

        public double similarity { get; set; }

    }
}

AdventureWorks/Controllers/EmployeeDepartmentHistoriesController.cs
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AdventureWorks.DAL;
using AdventureWorks.Models;

namespace AdventureWorks.Controllers
{
    public class EmployeeDepartmentHistoriesController : Controller
    {

        // GET: EmployeeDepartmentHistories/Details/5
        public ActionResult Details(int? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // the id parameter is not null, so convert it to int
            int currId = (int)id;
            EmployeeDepartmentHistoryContent edhc = new EmployeeDepartmentHistoryContent();

            // Display all departments(list) in which the employee has worked in the past, ordered by startdate and enddate.
            var departmentList = edhc.getFullDepartmentHistoryByEmployeeId(currId).OrderBy(s => s.StartDate).ThenBy(n => n.EndDate);

            // If the list is empty, a corresponding confirmation is given
            if (departmentList == null)
            {
                return HttpNotFound();
            }

            EmployeeContent ec = new EmployeeContent();

            // The name of the current employee is stored temporarily.
            //--------------------------------------------------------------
            Employees empContent = ec.getEmployeeNameById(currId);
            ViewBag.EmployeeFirstName = empContent.FirstName;
            ViewBag.EmployeeLastName = empContent.LastName;
            //--------------------------------------------------------------

            return View(departmentList);
        }
    }
}

AdventureWorks/Controllers/EmployeesController.cs
using System;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using AdventureWorks.DAL;
using System.Collections.Generic;
using AdventureWorks.Utils;
using AdventureWorks.Models;

namespace AdventureWorks.Controllers
{
    public class EmployeesController : Controller
    {

        public ActionResult Index(string sortOrder, string searchString)
        {
            // create new employeeContent object (DAL) 
            EmployeeContent epc = new EmployeeContent();

            // Determine all employees(List) using the DAL function 
            var employeeList = epc.getAllEmployees();
            List<string> firstLastNameList = new List<string>();

            // If the search string is not empty, the result set is reduced to the parameter to be searched in the "First name" and "Last name" columns.
            if (!String.IsNullOrEmpty(searchString))
            {
                ViewBag.SearchingFor = "Tabelle zeigt aktuell alle Treffer mit '" + searchString + "'"; 

                // Return a list containing the person names with the values we are looking for
                employeeList = employeeList.Where(s => s.LastName.ToLower().Contains(searchString.ToLower()) || s.FirstName.ToLower().Contains(searchString.ToLower())).ToList();

                // first idea of getting the similarities
                foreach (Employees content in employeeList)
                {
                    content.similarity = FuzzySearch.CalculateSimilarity(searchString.ToLower(), (content.FirstName.ToLower() + " " + content.LastName.ToLower()));
                }
            }

            // return the employeelist
            return View(employeeList);
        }

    }
}

AdventureWorks/Controllers/HomeController.cs
using System.Web.Mvc;

namespace AdventureWorks.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Beispielanwendung zur Adventure Works Cycles Datenbank.";

            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

AdventureWorks/Views/EmployeeDepartmentHistories/Details.cshtml
@model IEnumerable<AdventureWorks.Models.EmployeeDepartmentHistorys>
@using GridMvc.Html  

<div class="row">
    <div class="col-xs-12 col-md-8">
        @{
            ViewBag.Title = "Abteilungshistorie";
        }

        <h2>Abteilungshistorie von: @ViewBag.EmployeeFirstName @ViewBag.EmployeeLastName</h2>
        <br />
    </div>
</div>
<br />

<div class="code-cut">
    @Html.Grid(Model).Named("employeeDepartmentHistGrid").Columns(columns =>
    {
        columns.Add(c => c.BusinessEntityID).Titled("ID").SetWidth(50);
        columns.Add(c => c.StartDate).Titled("Startdatum").Format("{0:dd/MM/yyyy}").SetWidth(80);
        columns.Add(c => c.EndDate).Titled("Enddatum").Format("{0:dd/MM/yyyy}").SetWidth(80);
        columns.Add(c => c.DepartmentID).Titled("Abteilungsnummer").SetWidth(30);
        columns.Add(c => c.Name).Titled("Abteilungsname")
        .Encoded(false)
        .Sanitized(false)
        .SetWidth(30);
    }).WithPaging(10).Sortable(true).Selectable(true)
</div>
<br />
<p>
    @Html.ActionLink("Zurück zur Übersicht", "Index", "Employees")
</p>

AdventureWorks/Views/Employees/Index.cshtml
@model IEnumerable<AdventureWorks.Models.Employees>
@using GridMvc.Html  

<div class="row">
    <div class="col-xs-12 col-md-8">
        @{
            ViewBag.Title = "Index";
        }

        <h2>Mitarbeiterübersicht</h2>
        <br />
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-md-8">
        <form class="form-inline">
            <div class="form-group">
                <label for="nameSearchBoxLabel">Suche nach Name:</label>
                <input type="text" class="form-control" id="searchString" name="SearchString" placeholder="John Doe">
                <button type="submit" class="btn btn-default">Suchen</button>
            </div>
        </form>
    </div>
</div>

@if (ViewBag.SearchingFor != null)
{
<br />
<div class="row bg-warning"  style="text-align:center">
    <p class="col-xs-12 col-md-12">
        <br />
        <label for="resultLabel">@ViewBag.SearchingFor</label>
    </p>
</div>
}

<br />

<div id="astr" class="code-cut">
    @Html.Grid(Model).Named("employeeGrid").Columns(columns =>
    {
    columns.Add(c => c.BusinessEntityID).Titled("ID").Sanitized(false).Encoded(false).RenderValueAs(model => Html.ActionLink(model.EmployeeID,"Details", "EmployeeDepartmentHistories", new { id = model.BusinessEntityID }, null).ToHtmlString()).SetWidth(80);
    columns.Add(c => c.JobTitle).Titled("Titel").SetWidth(300);
    columns.Add(c => c.BirthDate).Titled("Geburtsdatum").Format("{0:dd/MM/yyyy}").SetWidth(80);
    columns.Add(c => c.FirstName).Titled("Vorname").SetWidth(150);
    columns.Add(c => c.MiddleName).Titled("Mittelname").SetWidth(150);
    columns.Add(c => c.LastName).Titled("Nachname").SetWidth(150)
    .Encoded(false)
    .Sanitized(false);
    columns.Add(o => o.similarity, true);
        }).WithPaging(10).Sortable(true).Selectable(true)

</div>
<br />

    @section Scripts {
        <script type="text/javascript">
        </script>
    }

AdventureWorks/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Message</h2>

<p>Im Auftrag der Aditus GmbH im Rahmen des Einstellungstest für Softwareentwickler.</p>
<p>Geschrieben von <a href="mailto:...">Stephan Müller</a></p> 

AdventureWorks/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h3>Aditus GmbH</h3>

<address>
    Karlsruher Straße 4<br />
    30880 Laatzen<br />
</address>

<address>
    <abbr title="Fon">Fon:</abbr>
    +49 511 866557-30<br />
    <abbr title="Fax">Fax:</abbr>
    +49 511 866557-57
</address>

<address>
    <strong>E-Mail:</strong>   <a href="mailto:...">Info@aditus.de</a>
</address>

AdventureWorks/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Adventure Works Cycles</h1>
    <p class="lead"> AdventureWorks-Beispieldatenbanken erstellt von Stepan Müller</p>
    <p></p>
    <p><a href="https://technet.microsoft.com/de-de/library/ms124825(v=sql.100).aspx" class="btn btn-primary btn-lg">Weitere Informationen &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <p>
            Adventure Works Cycles, das fiktive Unternehmen, auf dem die AdventureWorks-Beispieldatenbanken basieren, ist ein großes, multinationales Produktionsunternehmen.
            Das Unternehmen fertigt und verkauft Fahrräder aus Metall und Verbundwerkstoffen auf dem nordamerikanischen, 
            europäischen und asiatischen Markt. Der Hauptsitz befindet sich mit 290 Mitarbeitern in Bothell, Washington, während mehrere regionale 
            Vertriebsteams über die Zielmärkte hinweg verteilt sind.
        </p>
    </div>
    <div class="col-md-4">
        <p>m Jahr 2000 erwarb Adventure Works Cycles eine kleine Produktionsstätte namens Importadores Neptuno in Mexiko. Importadores Neptuno stellt 
        wichtige Bauteile für die Produktpalette von Adventure Works Cycles her. Diese Bauteile werden zur Endmontage an den Standort Bothell geliefert. 
        Seit 2001 ist Importadores Neptuno der alleinige Hersteller und Distributor der Produktgruppe Tourenräder.</p>
    </div>
    <div class="col-md-4">
        <p>Nach Abschluss eines erfolgreichen Geschäftsjahres ist Adventure Works Cycles daran interessiert, seinen Marktanteil durch intensivierten Verkauf an 
        gute Kunden, durch Erweiterung der Produktverfügbarkeit über eine externe Website und durch Senkung der Preise durch reduzierte 
        Produktionskosten zu vergrößern.</p>
    </div>

    <div class="col-md-4">
        <p>Quelle: <a href="https://technet.microsoft.com/de-de/library/ms124825(v=sql.100).aspx">Microsoft TechNet</a></p>
    </div>
</div>

AdventureWorks/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

AdventureWorks/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

AdventureWorks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Adventure Works Cycles</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Adventure Works Cycles", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Angestellte", "Index", "Employees")</li>
                    <li>@Html.ActionLink("Info", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Adventure Works Cycles</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/gridmvc")
    @RenderSection("scripts", required: false)
</body>
</html>